// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock_test.go -package=syncer
//

// Package syncer is a generated GoMock package.
package syncer

import (
	reflect "reflect"

	eventcore "github.com/jictyvoo/olhojogo/internal/domain/eventcore"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockRepository) Begin() (Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin")
	ret0, _ := ret[0].(Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockRepositoryMockRecorder) Begin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockRepository)(nil).Begin))
}

// RecordError mocks base method.
func (m *MockRepository) RecordError(provider eventcore.ProviderID, scope, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordError", provider, scope, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordError indicates an expected call of RecordError.
func (mr *MockRepositoryMockRecorder) RecordError(provider, scope, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordError", reflect.TypeOf((*MockRepository)(nil).RecordError), provider, scope, errMsg)
}

// SaveCursor mocks base method.
func (m *MockRepository) SaveCursor(provider eventcore.ProviderID, scope, cursor string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCursor", provider, scope, cursor)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCursor indicates an expected call of SaveCursor.
func (mr *MockRepositoryMockRecorder) SaveCursor(provider, scope, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCursor", reflect.TypeOf((*MockRepository)(nil).SaveCursor), provider, scope, cursor)
}

// MockTx is a mock of Tx interface.
type MockTx struct {
	ctrl     *gomock.Controller
	recorder *MockTxMockRecorder
	isgomock struct{}
}

// MockTxMockRecorder is the mock recorder for MockTx.
type MockTxMockRecorder struct {
	mock *MockTx
}

// NewMockTx creates a new mock instance.
func NewMockTx(ctrl *gomock.Controller) *MockTx {
	mock := &MockTx{ctrl: ctrl}
	mock.recorder = &MockTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTx) EXPECT() *MockTxMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockTx) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTxMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTx)(nil).Commit))
}

// Rollback mocks base method.
func (m *MockTx) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTxMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTx)(nil).Rollback))
}

// UpsertCompetition mocks base method.
func (m *MockTx) UpsertCompetition(c eventcore.Competition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCompetition", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCompetition indicates an expected call of UpsertCompetition.
func (mr *MockTxMockRecorder) UpsertCompetition(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCompetition", reflect.TypeOf((*MockTx)(nil).UpsertCompetition), c)
}

// UpsertFixture mocks base method.
func (m *MockTx) UpsertFixture(f eventcore.Fixture) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFixture", f)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertFixture indicates an expected call of UpsertFixture.
func (mr *MockTxMockRecorder) UpsertFixture(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFixture", reflect.TypeOf((*MockTx)(nil).UpsertFixture), f)
}

// UpsertFixtureParticipants mocks base method.
func (m *MockTx) UpsertFixtureParticipants(fixtureID eventcore.CanonicalID, parts []eventcore.FixtureParticipant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFixtureParticipants", fixtureID, parts)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertFixtureParticipants indicates an expected call of UpsertFixtureParticipants.
func (mr *MockTxMockRecorder) UpsertFixtureParticipants(fixtureID, parts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFixtureParticipants", reflect.TypeOf((*MockTx)(nil).UpsertFixtureParticipants), fixtureID, parts)
}

// UpsertGroup mocks base method.
func (m *MockTx) UpsertGroup(g eventcore.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertGroup", g)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertGroup indicates an expected call of UpsertGroup.
func (mr *MockTxMockRecorder) UpsertGroup(g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertGroup", reflect.TypeOf((*MockTx)(nil).UpsertGroup), g)
}

// UpsertParticipant mocks base method.
func (m *MockTx) UpsertParticipant(p eventcore.Participant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertParticipant", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertParticipant indicates an expected call of UpsertParticipant.
func (mr *MockTxMockRecorder) UpsertParticipant(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertParticipant", reflect.TypeOf((*MockTx)(nil).UpsertParticipant), p)
}

// UpsertResult mocks base method.
func (m *MockTx) UpsertResult(res eventcore.Result) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertResult", res)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertResult indicates an expected call of UpsertResult.
func (mr *MockTxMockRecorder) UpsertResult(res any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertResult", reflect.TypeOf((*MockTx)(nil).UpsertResult), res)
}

// UpsertSeason mocks base method.
func (m *MockTx) UpsertSeason(s eventcore.Season) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSeason", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertSeason indicates an expected call of UpsertSeason.
func (mr *MockTxMockRecorder) UpsertSeason(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSeason", reflect.TypeOf((*MockTx)(nil).UpsertSeason), s)
}

// UpsertStage mocks base method.
func (m *MockTx) UpsertStage(s eventcore.Stage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertStage", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertStage indicates an expected call of UpsertStage.
func (mr *MockTxMockRecorder) UpsertStage(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertStage", reflect.TypeOf((*MockTx)(nil).UpsertStage), s)
}

// UpsertStanding mocks base method.
func (m *MockTx) UpsertStanding(s eventcore.Standing) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertStanding", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertStanding indicates an expected call of UpsertStanding.
func (mr *MockTxMockRecorder) UpsertStanding(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertStanding", reflect.TypeOf((*MockTx)(nil).UpsertStanding), s)
}

// UpsertVenue mocks base method.
func (m *MockTx) UpsertVenue(v eventcore.Venue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertVenue", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertVenue indicates an expected call of UpsertVenue.
func (mr *MockTxMockRecorder) UpsertVenue(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertVenue", reflect.TypeOf((*MockTx)(nil).UpsertVenue), v)
}
