// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: countries.sql

package dbgen

import (
	"context"
	"database/sql"
)

const GetCountryByIOC = `-- name: GetCountryByIOC :one
SELECT id, iso2, iso3, ioc_code, name, code_num, population, area_km2, gdp_usd FROM countries WHERE ioc_code = ? LIMIT 1
`

func (q *Queries) GetCountryByIOC(ctx context.Context, iocCode sql.NullString) (Country, error) {
	row := q.db.QueryRowContext(ctx, GetCountryByIOC, iocCode)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Iso2,
		&i.Iso3,
		&i.IocCode,
		&i.Name,
		&i.CodeNum,
		&i.Population,
		&i.AreaKm2,
		&i.GdpUsd,
	)
	return i, err
}

const GetCountryByISO2 = `-- name: GetCountryByISO2 :one
SELECT id, iso2, iso3, ioc_code, name, code_num, population, area_km2, gdp_usd FROM countries WHERE iso2 = ? LIMIT 1
`

func (q *Queries) GetCountryByISO2(ctx context.Context, iso2 string) (Country, error) {
	row := q.db.QueryRowContext(ctx, GetCountryByISO2, iso2)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Iso2,
		&i.Iso3,
		&i.IocCode,
		&i.Name,
		&i.CodeNum,
		&i.Population,
		&i.AreaKm2,
		&i.GdpUsd,
	)
	return i, err
}

const GetCountryByISO3 = `-- name: GetCountryByISO3 :one
SELECT id, iso2, iso3, ioc_code, name, code_num, population, area_km2, gdp_usd FROM countries WHERE iso3 = ? LIMIT 1
`

func (q *Queries) GetCountryByISO3(ctx context.Context, iso3 string) (Country, error) {
	row := q.db.QueryRowContext(ctx, GetCountryByISO3, iso3)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Iso2,
		&i.Iso3,
		&i.IocCode,
		&i.Name,
		&i.CodeNum,
		&i.Population,
		&i.AreaKm2,
		&i.GdpUsd,
	)
	return i, err
}

const ListCountries = `-- name: ListCountries :many
SELECT id, iso2, iso3, ioc_code, name, code_num, population, area_km2, gdp_usd FROM countries ORDER BY name ASC
`

func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.QueryContext(ctx, ListCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Iso2,
			&i.Iso3,
			&i.IocCode,
			&i.Name,
			&i.CodeNum,
			&i.Population,
			&i.AreaKm2,
			&i.GdpUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertCountry = `-- name: UpsertCountry :exec
INSERT IGNORE INTO countries (iso2, iso3, ioc_code, name, code_num, population, area_km2, gdp_usd)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type UpsertCountryParams struct {
	Iso2       string          `db:"iso2"`
	Iso3       string          `db:"iso3"`
	IocCode    sql.NullString  `db:"ioc_code"`
	Name       string          `db:"name"`
	CodeNum    sql.NullInt64   `db:"code_num"`
	Population sql.NullInt64   `db:"population"`
	AreaKm2    sql.NullFloat64 `db:"area_km2"`
	GdpUsd     sql.NullFloat64 `db:"gdp_usd"`
}

func (q *Queries) UpsertCountry(ctx context.Context, arg UpsertCountryParams) error {
	_, err := q.db.ExecContext(ctx, UpsertCountry,
		arg.Iso2,
		arg.Iso3,
		arg.IocCode,
		arg.Name,
		arg.CodeNum,
		arg.Population,
		arg.AreaKm2,
		arg.GdpUsd,
	)
	return err
}
