// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discord_events.sql

package dbgen

import (
	"context"
	"database/sql"
)

const GetDiscordEventByDiscordID = `-- name: GetDiscordEventByDiscordID :one
SELECT id, created_at, updated_at, guild_id, discord_event_id, status, last_checksum, fixture_id FROM discord_events WHERE discord_event_id = ? LIMIT 1
`

func (q *Queries) GetDiscordEventByDiscordID(ctx context.Context, discordEventID string) (DiscordEvent, error) {
	row := q.db.QueryRowContext(ctx, GetDiscordEventByDiscordID, discordEventID)
	var i DiscordEvent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuildID,
		&i.DiscordEventID,
		&i.Status,
		&i.LastChecksum,
		&i.FixtureID,
	)
	return i, err
}

const GetDiscordEventByFixture = `-- name: GetDiscordEventByFixture :one
SELECT id, created_at, updated_at, guild_id, discord_event_id, status, last_checksum, fixture_id FROM discord_events WHERE fixture_id = ? AND guild_id = ? LIMIT 1
`

type GetDiscordEventByFixtureParams struct {
	FixtureID []byte `db:"fixture_id"`
	GuildID   string `db:"guild_id"`
}

func (q *Queries) GetDiscordEventByFixture(ctx context.Context, arg GetDiscordEventByFixtureParams) (DiscordEvent, error) {
	row := q.db.QueryRowContext(ctx, GetDiscordEventByFixture, arg.FixtureID, arg.GuildID)
	var i DiscordEvent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GuildID,
		&i.DiscordEventID,
		&i.Status,
		&i.LastChecksum,
		&i.FixtureID,
	)
	return i, err
}

const ListActiveDiscordEvents = `-- name: ListActiveDiscordEvents :many
SELECT id, created_at, updated_at, guild_id, discord_event_id, status, last_checksum, fixture_id FROM discord_events
WHERE guild_id = ? AND status NOT IN ('completed', 'cancelled')
ORDER BY updated_at DESC
`

func (q *Queries) ListActiveDiscordEvents(ctx context.Context, guildID string) ([]DiscordEvent, error) {
	rows, err := q.db.QueryContext(ctx, ListActiveDiscordEvents, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscordEvent{}
	for rows.Next() {
		var i DiscordEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuildID,
			&i.DiscordEventID,
			&i.Status,
			&i.LastChecksum,
			&i.FixtureID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateDiscordEventStatus = `-- name: UpdateDiscordEventStatus :exec
UPDATE discord_events SET status = ? WHERE fixture_id = ? AND guild_id = ?
`

type UpdateDiscordEventStatusParams struct {
	Status    string `db:"status"`
	FixtureID []byte `db:"fixture_id"`
	GuildID   string `db:"guild_id"`
}

func (q *Queries) UpdateDiscordEventStatus(ctx context.Context, arg UpdateDiscordEventStatusParams) error {
	_, err := q.db.ExecContext(ctx, UpdateDiscordEventStatus, arg.Status, arg.FixtureID, arg.GuildID)
	return err
}

const UpsertDiscordEvent = `-- name: UpsertDiscordEvent :exec
INSERT INTO discord_events (fixture_id, guild_id, discord_event_id, status, last_checksum)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    discord_event_id = VALUES(discord_event_id),
    status           = VALUES(status),
    last_checksum    = VALUES(last_checksum)
`

type UpsertDiscordEventParams struct {
	FixtureID      []byte         `db:"fixture_id"`
	GuildID        string         `db:"guild_id"`
	DiscordEventID string         `db:"discord_event_id"`
	Status         string         `db:"status"`
	LastChecksum   sql.NullString `db:"last_checksum"`
}

func (q *Queries) UpsertDiscordEvent(ctx context.Context, arg UpsertDiscordEventParams) error {
	_, err := q.db.ExecContext(ctx, UpsertDiscordEvent,
		arg.FixtureID,
		arg.GuildID,
		arg.DiscordEventID,
		arg.Status,
		arg.LastChecksum,
	)
	return err
}
