// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fixtures.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const GetFixture = `-- name: GetFixture :one
SELECT id, created_at, updated_at, provider_id, external_key, group_id, venue_id, name, starts_at, ends_at, status, checksum, stage_id FROM fixtures WHERE id = ? LIMIT 1
`

func (q *Queries) GetFixture(ctx context.Context, id []byte) (Fixture, error) {
	row := q.db.QueryRowContext(ctx, GetFixture, id)
	var i Fixture
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.ExternalKey,
		&i.GroupID,
		&i.VenueID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.Checksum,
		&i.StageID,
	)
	return i, err
}

const GetFixtureByExternalKey = `-- name: GetFixtureByExternalKey :one
SELECT id, created_at, updated_at, provider_id, external_key, group_id, venue_id, name, starts_at, ends_at, status, checksum, stage_id FROM fixtures WHERE provider_id = ? AND external_key = ? LIMIT 1
`

type GetFixtureByExternalKeyParams struct {
	ProviderID  string `db:"provider_id"`
	ExternalKey string `db:"external_key"`
}

func (q *Queries) GetFixtureByExternalKey(ctx context.Context, arg GetFixtureByExternalKeyParams) (Fixture, error) {
	row := q.db.QueryRowContext(ctx, GetFixtureByExternalKey, arg.ProviderID, arg.ExternalKey)
	var i Fixture
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.ExternalKey,
		&i.GroupID,
		&i.VenueID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.Checksum,
		&i.StageID,
	)
	return i, err
}

const ListFixturesByDay = `-- name: ListFixturesByDay :many
SELECT id, created_at, updated_at, provider_id, external_key, group_id, venue_id, name, starts_at, ends_at, status, checksum, stage_id FROM fixtures
WHERE provider_id = ?
  AND starts_at >= ?
  AND starts_at < ?
ORDER BY starts_at ASC
`

type ListFixturesByDayParams struct {
	ProviderID string    `db:"provider_id"`
	StartsAt   time.Time `db:"starts_at"`
	StartsAt_2 time.Time `db:"starts_at_2"`
}

func (q *Queries) ListFixturesByDay(ctx context.Context, arg ListFixturesByDayParams) ([]Fixture, error) {
	rows, err := q.db.QueryContext(ctx, ListFixturesByDay, arg.ProviderID, arg.StartsAt, arg.StartsAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fixture{}
	for rows.Next() {
		var i Fixture
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderID,
			&i.ExternalKey,
			&i.GroupID,
			&i.VenueID,
			&i.Name,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.Checksum,
			&i.StageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListFixturesByStatus = `-- name: ListFixturesByStatus :many
SELECT id, created_at, updated_at, provider_id, external_key, group_id, venue_id, name, starts_at, ends_at, status, checksum, stage_id FROM fixtures WHERE status = ? ORDER BY starts_at ASC
`

func (q *Queries) ListFixturesByStatus(ctx context.Context, status string) ([]Fixture, error) {
	rows, err := q.db.QueryContext(ctx, ListFixturesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fixture{}
	for rows.Next() {
		var i Fixture
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderID,
			&i.ExternalKey,
			&i.GroupID,
			&i.VenueID,
			&i.Name,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.Checksum,
			&i.StageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListFixturesStartingBefore = `-- name: ListFixturesStartingBefore :many
SELECT id, created_at, updated_at, provider_id, external_key, group_id, venue_id, name, starts_at, ends_at, status, checksum, stage_id FROM fixtures
WHERE starts_at <= ?
  AND status NOT IN ('finished', 'cancelled')
ORDER BY starts_at ASC
`

func (q *Queries) ListFixturesStartingBefore(ctx context.Context, startsAt time.Time) ([]Fixture, error) {
	rows, err := q.db.QueryContext(ctx, ListFixturesStartingBefore, startsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fixture{}
	for rows.Next() {
		var i Fixture
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderID,
			&i.ExternalKey,
			&i.GroupID,
			&i.VenueID,
			&i.Name,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.Checksum,
			&i.StageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateFixtureChecksum = `-- name: UpdateFixtureChecksum :exec
UPDATE fixtures SET checksum = ? WHERE id = ?
`

type UpdateFixtureChecksumParams struct {
	Checksum sql.NullString `db:"checksum"`
	ID       []byte         `db:"id"`
}

func (q *Queries) UpdateFixtureChecksum(ctx context.Context, arg UpdateFixtureChecksumParams) error {
	_, err := q.db.ExecContext(ctx, UpdateFixtureChecksum, arg.Checksum, arg.ID)
	return err
}

const UpdateFixtureStatus = `-- name: UpdateFixtureStatus :exec
UPDATE fixtures SET status = ? WHERE id = ?
`

type UpdateFixtureStatusParams struct {
	Status string `db:"status"`
	ID     []byte `db:"id"`
}

func (q *Queries) UpdateFixtureStatus(ctx context.Context, arg UpdateFixtureStatusParams) error {
	_, err := q.db.ExecContext(ctx, UpdateFixtureStatus, arg.Status, arg.ID)
	return err
}

const UpsertFixture = `-- name: UpsertFixture :exec
INSERT INTO fixtures (
    id, provider_id, external_key, stage_id, group_id, venue_id,
    name, starts_at, ends_at, status, checksum
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    name       = VALUES(name),
    starts_at  = VALUES(starts_at),
    ends_at    = VALUES(ends_at),
    status     = VALUES(status),
    checksum   = VALUES(checksum),
    group_id   = VALUES(group_id),
    venue_id   = VALUES(venue_id)
`

type UpsertFixtureParams struct {
	ID          []byte         `db:"id"`
	ProviderID  string         `db:"provider_id"`
	ExternalKey string         `db:"external_key"`
	StageID     []byte         `db:"stage_id"`
	GroupID     sql.NullString `db:"group_id"`
	VenueID     sql.NullString `db:"venue_id"`
	Name        string         `db:"name"`
	StartsAt    time.Time      `db:"starts_at"`
	EndsAt      time.Time      `db:"ends_at"`
	Status      string         `db:"status"`
	Checksum    sql.NullString `db:"checksum"`
}

func (q *Queries) UpsertFixture(ctx context.Context, arg UpsertFixtureParams) error {
	_, err := q.db.ExecContext(ctx, UpsertFixture,
		arg.ID,
		arg.ProviderID,
		arg.ExternalKey,
		arg.StageID,
		arg.GroupID,
		arg.VenueID,
		arg.Name,
		arg.StartsAt,
		arg.EndsAt,
		arg.Status,
		arg.Checksum,
	)
	return err
}
