// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package dbgen

import (
	"context"
)

const GetGroup = `-- name: GetGroup :one
SELECT id, created_at, updated_at, provider_id, external_key, name, stage_id FROM ` + "`" + `groups` + "`" + ` WHERE id = ? LIMIT 1
`

func (q *Queries) GetGroup(ctx context.Context, id []byte) (Group, error) {
	row := q.db.QueryRowContext(ctx, GetGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.ExternalKey,
		&i.Name,
		&i.StageID,
	)
	return i, err
}

const UpsertGroup = `-- name: UpsertGroup :exec
INSERT INTO ` + "`" + `groups` + "`" + ` (
    id, provider_id, external_key, name, stage_id
) VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    name     = VALUES(name),
    stage_id = VALUES(stage_id)
`

type UpsertGroupParams struct {
	ID          []byte `db:"id"`
	ProviderID  string `db:"provider_id"`
	ExternalKey string `db:"external_key"`
	Name        string `db:"name"`
	StageID     []byte `db:"stage_id"`
}

func (q *Queries) UpsertGroup(ctx context.Context, arg UpsertGroupParams) error {
	_, err := q.db.ExecContext(ctx, UpsertGroup,
		arg.ID,
		arg.ProviderID,
		arg.ExternalKey,
		arg.Name,
		arg.StageID,
	)
	return err
}
