// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"time"
)

type Alert struct {
	ID        []byte    `db:"id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
	Kind      string    `db:"kind"`
	FixtureID []byte    `db:"fixture_id"`
}

type Competition struct {
	ID          []byte         `db:"id"`
	CreatedAt   time.Time      `db:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at"`
	ProviderID  string         `db:"provider_id"`
	ExternalKey string         `db:"external_key"`
	Code        sql.NullString `db:"code"`
	Name        string         `db:"name"`
	Discipline  sql.NullString `db:"discipline"`
}

type Country struct {
	ID         int64           `db:"id"`
	Iso2       string          `db:"iso2"`
	Iso3       string          `db:"iso3"`
	IocCode    sql.NullString  `db:"ioc_code"`
	Name       string          `db:"name"`
	CodeNum    sql.NullInt64   `db:"code_num"`
	Population sql.NullInt64   `db:"population"`
	AreaKm2    sql.NullFloat64 `db:"area_km2"`
	GdpUsd     sql.NullFloat64 `db:"gdp_usd"`
}

type DiscordEvent struct {
	ID             int64          `db:"id"`
	CreatedAt      time.Time      `db:"created_at"`
	UpdatedAt      time.Time      `db:"updated_at"`
	GuildID        string         `db:"guild_id"`
	DiscordEventID string         `db:"discord_event_id"`
	Status         string         `db:"status"`
	LastChecksum   sql.NullString `db:"last_checksum"`
	FixtureID      []byte         `db:"fixture_id"`
}

type Fixture struct {
	ID          []byte         `db:"id"`
	CreatedAt   time.Time      `db:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at"`
	ProviderID  string         `db:"provider_id"`
	ExternalKey string         `db:"external_key"`
	GroupID     sql.NullString `db:"group_id"`
	VenueID     sql.NullString `db:"venue_id"`
	Name        string         `db:"name"`
	StartsAt    time.Time      `db:"starts_at"`
	EndsAt      time.Time      `db:"ends_at"`
	Status      string         `db:"status"`
	Checksum    sql.NullString `db:"checksum"`
	StageID     []byte         `db:"stage_id"`
}

type FixtureParticipant struct {
	ID            int64          `db:"id"`
	ParticipantID []byte         `db:"participant_id"`
	Role          sql.NullString `db:"role"`
	FixtureID     []byte         `db:"fixture_id"`
}

type Group struct {
	ID          []byte    `db:"id"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
	ProviderID  string    `db:"provider_id"`
	ExternalKey string    `db:"external_key"`
	Name        string    `db:"name"`
	StageID     []byte    `db:"stage_id"`
}

type Notification struct {
	ID        []byte         `db:"id"`
	CreatedAt time.Time      `db:"created_at"`
	UpdatedAt time.Time      `db:"updated_at"`
	ChannelID sql.NullString `db:"channel_id"`
	MessageID sql.NullString `db:"message_id"`
	Status    string         `db:"status"`
	Checksum  sql.NullString `db:"checksum"`
	SentAt    sql.NullTime   `db:"sent_at"`
	AlertID   []byte         `db:"alert_id"`
}

type Participant struct {
	ID          []byte         `db:"id"`
	CreatedAt   time.Time      `db:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at"`
	ProviderID  string         `db:"provider_id"`
	ExternalKey string         `db:"external_key"`
	Kind        string         `db:"kind"`
	Name        string         `db:"name"`
	Code        sql.NullString `db:"code"`
	CountryIso  sql.NullString `db:"country_iso"`
	Gender      sql.NullString `db:"gender"`
}

type Result struct {
	ID            int64          `db:"id"`
	CreatedAt     time.Time      `db:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at"`
	ParticipantID []byte         `db:"participant_id"`
	Position      sql.NullInt64  `db:"position"`
	Score         sql.NullString `db:"score"`
	RawMark       sql.NullString `db:"raw_mark"`
	Outcome       sql.NullString `db:"outcome"`
	FixtureID     []byte         `db:"fixture_id"`
}

type Season struct {
	ID            []byte    `db:"id"`
	CreatedAt     time.Time `db:"created_at"`
	UpdatedAt     time.Time `db:"updated_at"`
	ProviderID    string    `db:"provider_id"`
	ExternalKey   string    `db:"external_key"`
	Name          string    `db:"name"`
	StartsOn      time.Time `db:"starts_on"`
	EndsOn        time.Time `db:"ends_on"`
	CompetitionID []byte    `db:"competition_id"`
}

type Stage struct {
	ID          []byte    `db:"id"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
	ProviderID  string    `db:"provider_id"`
	ExternalKey string    `db:"external_key"`
	Name        string    `db:"name"`
	Ord         int64     `db:"ord"`
	SeasonID    []byte    `db:"season_id"`
}

type Standing struct {
	ID            int64     `db:"id"`
	CreatedAt     time.Time `db:"created_at"`
	UpdatedAt     time.Time `db:"updated_at"`
	StageID       []byte    `db:"stage_id"`
	ParticipantID []byte    `db:"participant_id"`
	Rank          int64     `db:"rank"`
	Points        int64     `db:"points"`
}

type Subscription struct {
	ID        int64          `db:"id"`
	CreatedAt time.Time      `db:"created_at"`
	UpdatedAt time.Time      `db:"updated_at"`
	GuildID   string         `db:"guild_id"`
	UserID    string         `db:"user_id"`
	Kind      string         `db:"kind"`
	Value     sql.NullString `db:"value"`
}

type SyncState struct {
	ID           int64          `db:"id"`
	ProviderID   string         `db:"provider_id"`
	Scope        string         `db:"scope"`
	Cursor       sql.NullString `db:"cursor"`
	LastSyncedAt sql.NullTime   `db:"last_synced_at"`
	LastError    sql.NullString `db:"last_error"`
}

type Venue struct {
	ID          []byte         `db:"id"`
	CreatedAt   time.Time      `db:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at"`
	ProviderID  string         `db:"provider_id"`
	ExternalKey string         `db:"external_key"`
	Name        string         `db:"name"`
	City        sql.NullString `db:"city"`
	CountryIso  sql.NullString `db:"country_iso"`
}
