// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participants.sql

package dbgen

import (
	"context"
	"database/sql"
)

const GetParticipant = `-- name: GetParticipant :one
SELECT id, created_at, updated_at, provider_id, external_key, kind, name, code, country_iso, gender FROM participants WHERE id = ? LIMIT 1
`

func (q *Queries) GetParticipant(ctx context.Context, id []byte) (Participant, error) {
	row := q.db.QueryRowContext(ctx, GetParticipant, id)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.ExternalKey,
		&i.Kind,
		&i.Name,
		&i.Code,
		&i.CountryIso,
		&i.Gender,
	)
	return i, err
}

const GetParticipantByExternalKey = `-- name: GetParticipantByExternalKey :one
SELECT id, created_at, updated_at, provider_id, external_key, kind, name, code, country_iso, gender FROM participants WHERE provider_id = ? AND external_key = ? LIMIT 1
`

type GetParticipantByExternalKeyParams struct {
	ProviderID  string `db:"provider_id"`
	ExternalKey string `db:"external_key"`
}

func (q *Queries) GetParticipantByExternalKey(ctx context.Context, arg GetParticipantByExternalKeyParams) (Participant, error) {
	row := q.db.QueryRowContext(ctx, GetParticipantByExternalKey, arg.ProviderID, arg.ExternalKey)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.ExternalKey,
		&i.Kind,
		&i.Name,
		&i.Code,
		&i.CountryIso,
		&i.Gender,
	)
	return i, err
}

const ListFixtureParticipants = `-- name: ListFixtureParticipants :many
SELECT fp.fixture_id, fp.participant_id, fp.role
FROM fixture_participants fp
WHERE fp.fixture_id = ?
`

type ListFixtureParticipantsRow struct {
	FixtureID     []byte         `db:"fixture_id"`
	ParticipantID []byte         `db:"participant_id"`
	Role          sql.NullString `db:"role"`
}

func (q *Queries) ListFixtureParticipants(ctx context.Context, fixtureID []byte) ([]ListFixtureParticipantsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListFixtureParticipants, fixtureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFixtureParticipantsRow{}
	for rows.Next() {
		var i ListFixtureParticipantsRow
		if err := rows.Scan(&i.FixtureID, &i.ParticipantID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListParticipantsByFixture = `-- name: ListParticipantsByFixture :many
SELECT p.id, p.created_at, p.updated_at, p.provider_id, p.external_key, p.kind, p.name, p.code, p.country_iso, p.gender
FROM participants p
JOIN fixture_participants fp ON fp.participant_id = p.id
WHERE fp.fixture_id = ?
`

func (q *Queries) ListParticipantsByFixture(ctx context.Context, fixtureID []byte) ([]Participant, error) {
	rows, err := q.db.QueryContext(ctx, ListParticipantsByFixture, fixtureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Participant{}
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderID,
			&i.ExternalKey,
			&i.Kind,
			&i.Name,
			&i.Code,
			&i.CountryIso,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertFixtureParticipant = `-- name: UpsertFixtureParticipant :exec
INSERT INTO fixture_participants (fixture_id, participant_id, role)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE role = VALUES(role)
`

type UpsertFixtureParticipantParams struct {
	FixtureID     []byte         `db:"fixture_id"`
	ParticipantID []byte         `db:"participant_id"`
	Role          sql.NullString `db:"role"`
}

func (q *Queries) UpsertFixtureParticipant(ctx context.Context, arg UpsertFixtureParticipantParams) error {
	_, err := q.db.ExecContext(ctx, UpsertFixtureParticipant, arg.FixtureID, arg.ParticipantID, arg.Role)
	return err
}

const UpsertParticipant = `-- name: UpsertParticipant :exec
INSERT INTO participants (
    id, provider_id, external_key, kind, name, code, country_iso, gender
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    name        = VALUES(name),
    code        = VALUES(code),
    country_iso = VALUES(country_iso),
    gender      = VALUES(gender)
`

type UpsertParticipantParams struct {
	ID          []byte         `db:"id"`
	ProviderID  string         `db:"provider_id"`
	ExternalKey string         `db:"external_key"`
	Kind        string         `db:"kind"`
	Name        string         `db:"name"`
	Code        sql.NullString `db:"code"`
	CountryIso  sql.NullString `db:"country_iso"`
	Gender      sql.NullString `db:"gender"`
}

func (q *Queries) UpsertParticipant(ctx context.Context, arg UpsertParticipantParams) error {
	_, err := q.db.ExecContext(ctx, UpsertParticipant,
		arg.ID,
		arg.ProviderID,
		arg.ExternalKey,
		arg.Kind,
		arg.Name,
		arg.Code,
		arg.CountryIso,
		arg.Gender,
	)
	return err
}
