// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stages.sql

package dbgen

import (
	"context"
)

const GetStage = `-- name: GetStage :one
SELECT id, created_at, updated_at, provider_id, external_key, name, ord, season_id FROM stages WHERE id = ? LIMIT 1
`

func (q *Queries) GetStage(ctx context.Context, id []byte) (Stage, error) {
	row := q.db.QueryRowContext(ctx, GetStage, id)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.ExternalKey,
		&i.Name,
		&i.Ord,
		&i.SeasonID,
	)
	return i, err
}

const UpsertStage = `-- name: UpsertStage :exec
INSERT INTO stages (
    id, provider_id, external_key, name, ord, season_id
) VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    name      = VALUES(name),
    ord       = VALUES(ord),
    season_id = VALUES(season_id)
`

type UpsertStageParams struct {
	ID          []byte `db:"id"`
	ProviderID  string `db:"provider_id"`
	ExternalKey string `db:"external_key"`
	Name        string `db:"name"`
	Ord         int64  `db:"ord"`
	SeasonID    []byte `db:"season_id"`
}

func (q *Queries) UpsertStage(ctx context.Context, arg UpsertStageParams) error {
	_, err := q.db.ExecContext(ctx, UpsertStage,
		arg.ID,
		arg.ProviderID,
		arg.ExternalKey,
		arg.Name,
		arg.Ord,
		arg.SeasonID,
	)
	return err
}
