// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: standings.sql

package dbgen

import (
	"context"
)

const ListStandingsByStage = `-- name: ListStandingsByStage :many
SELECT id, created_at, updated_at, stage_id, participant_id, ` + "`" + `rank` + "`" + `, points FROM standings WHERE stage_id = ? ORDER BY ` + "`" + `rank` + "`" + ` ASC
`

func (q *Queries) ListStandingsByStage(ctx context.Context, stageID []byte) ([]Standing, error) {
	rows, err := q.db.QueryContext(ctx, ListStandingsByStage, stageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Standing{}
	for rows.Next() {
		var i Standing
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StageID,
			&i.ParticipantID,
			&i.Rank,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertStanding = `-- name: UpsertStanding :exec
INSERT INTO standings (
    stage_id, participant_id, ` + "`" + `rank` + "`" + `, points
) VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    ` + "`" + `rank` + "`" + ` = VALUES(` + "`" + `rank` + "`" + `),
    points = VALUES(points)
`

type UpsertStandingParams struct {
	StageID       []byte `db:"stage_id"`
	ParticipantID []byte `db:"participant_id"`
	Rank          int64  `db:"rank"`
	Points        int64  `db:"points"`
}

func (q *Queries) UpsertStanding(ctx context.Context, arg UpsertStandingParams) error {
	_, err := q.db.ExecContext(ctx, UpsertStanding,
		arg.StageID,
		arg.ParticipantID,
		arg.Rank,
		arg.Points,
	)
	return err
}
