// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_states.sql

package dbgen

import (
	"context"
	"database/sql"
)

const GetSyncState = `-- name: GetSyncState :one
SELECT id, provider_id, scope, ` + "`" + `cursor` + "`" + `, last_synced_at, last_error FROM sync_states WHERE provider_id = ? AND scope = ? LIMIT 1
`

type GetSyncStateParams struct {
	ProviderID string `db:"provider_id"`
	Scope      string `db:"scope"`
}

func (q *Queries) GetSyncState(ctx context.Context, arg GetSyncStateParams) (SyncState, error) {
	row := q.db.QueryRowContext(ctx, GetSyncState, arg.ProviderID, arg.Scope)
	var i SyncState
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Scope,
		&i.Cursor,
		&i.LastSyncedAt,
		&i.LastError,
	)
	return i, err
}

const SetSyncStateError = `-- name: SetSyncStateError :exec
UPDATE sync_states SET last_error = ?, last_synced_at = NOW()
WHERE provider_id = ? AND scope = ?
`

type SetSyncStateErrorParams struct {
	LastError  sql.NullString `db:"last_error"`
	ProviderID string         `db:"provider_id"`
	Scope      string         `db:"scope"`
}

func (q *Queries) SetSyncStateError(ctx context.Context, arg SetSyncStateErrorParams) error {
	_, err := q.db.ExecContext(ctx, SetSyncStateError, arg.LastError, arg.ProviderID, arg.Scope)
	return err
}

const UpsertSyncState = `-- name: UpsertSyncState :exec
INSERT INTO sync_states (provider_id, scope, ` + "`" + `cursor` + "`" + `, last_synced_at, last_error)
VALUES (?, ?, ?, NOW(), NULL)
ON DUPLICATE KEY UPDATE
    ` + "`" + `cursor` + "`" + `         = VALUES(` + "`" + `cursor` + "`" + `),
    last_synced_at = NOW(),
    last_error     = NULL
`

type UpsertSyncStateParams struct {
	ProviderID string         `db:"provider_id"`
	Scope      string         `db:"scope"`
	Cursor     sql.NullString `db:"cursor"`
}

func (q *Queries) UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) error {
	_, err := q.db.ExecContext(ctx, UpsertSyncState, arg.ProviderID, arg.Scope, arg.Cursor)
	return err
}
