// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venues.sql

package dbgen

import (
	"context"
	"database/sql"
)

const GetVenue = `-- name: GetVenue :one
SELECT id, created_at, updated_at, provider_id, external_key, name, city, country_iso FROM venues WHERE id = ? LIMIT 1
`

func (q *Queries) GetVenue(ctx context.Context, id []byte) (Venue, error) {
	row := q.db.QueryRowContext(ctx, GetVenue, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.ExternalKey,
		&i.Name,
		&i.City,
		&i.CountryIso,
	)
	return i, err
}

const UpsertVenue = `-- name: UpsertVenue :exec
INSERT INTO venues (
    id, provider_id, external_key, name, city, country_iso
) VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    name        = VALUES(name),
    city        = VALUES(city),
    country_iso = VALUES(country_iso)
`

type UpsertVenueParams struct {
	ID          []byte         `db:"id"`
	ProviderID  string         `db:"provider_id"`
	ExternalKey string         `db:"external_key"`
	Name        string         `db:"name"`
	City        sql.NullString `db:"city"`
	CountryIso  sql.NullString `db:"country_iso"`
}

func (q *Queries) UpsertVenue(ctx context.Context, arg UpsertVenueParams) error {
	_, err := q.db.ExecContext(ctx, UpsertVenue,
		arg.ID,
		arg.ProviderID,
		arg.ExternalKey,
		arg.Name,
		arg.City,
		arg.CountryIso,
	)
	return err
}
