version: "3"

dotenv: [ './database/local.newdb.env' ]

includes:
  main:
    taskfile: ./Taskfile.build.yml
    dir: .
  docker:
    taskfile: ./Taskfile.docker.yml
    dir: .
  database:
    taskfile: ./database/Taskfile.yml
    dir: ./database
  tools:
    taskfile: ./tools/Taskfile.yml
    dir: ./tools

vars:
  TEST_CMD: "go test ./..."

tasks:
  default:
    desc: Run the default commands
    cmds:
      - task: dev-env:up
      - task: database:migration:apply
        vars:
          DIALECT: mysql
          DB_URL: mysql://{{.MYSQL_USER}}:{{.MYSQL_PASSWORD}}@localhost:3306/{{.MYSQL_DATABASE}}?multiStatements=true

  dev-env:up:
    desc: Up all development required environment
    cmds:
      - task: docker:stop
      - task: docker:run
        vars:
          OPTIONS: "--wait"
