// Command seedgen generates idempotent country seed migrations for SQLite and MySQL
// from database/seed/countries.json.
//
//	go run ./tools/seedgen
//
// Flags:
//
//	-source path/to/countries.json   (default database/seed/countries.json)
//	-out    path/to/database/migrations (default database/migrations)
//	-ts     timestamp prefix         (default 20260101000000)
//
// The generator is deterministic: the same input + timestamp produces byte-identical
// migration files, so re-running it after a no-op change yields no diff.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type rawCountry struct {
	Name       string   `json:"Name"`
	CodeNum    string   `json:"CodeNum"`
	ISOCode    []string `json:"ISOCode"`
	IOCCode    string   `json:"IOCCode"`
	Population int64    `json:"Population"`
	AreaKm2    float64  `json:"AreaKm2"`
	GDPUSD     string   `json:"GDPUSD"`
}

type entry struct {
	IOC, ISO2, ISO3, Name string
	CodeNum               *int
	Population            int64
	AreaKm2               float64
}

func main() {
	source := flag.String("source", "database/seed/countries.json", "path to countries.json")
	out := flag.String("out", "database/migrations", "migrations root directory")
	ts := flag.String("ts", "20260101000000", "timestamp prefix for the migration filename")
	flag.Parse()

	raw, err := os.ReadFile(*source)
	if err != nil {
		log.Fatalf("seedgen: read source: %v", err)
	}

	var byIOC map[string]rawCountry
	if err := json.Unmarshal(raw, &byIOC); err != nil {
		log.Fatalf("seedgen: parse json: %v", err)
	}

	entries := make([]entry, 0, len(byIOC))
	for ioc, c := range byIOC {
		if len(c.ISOCode) < 2 {
			continue
		}
		e := entry{
			IOC:        ioc,
			ISO2:       c.ISOCode[0],
			ISO3:       c.ISOCode[1],
			Name:       c.Name,
			Population: c.Population,
			AreaKm2:    c.AreaKm2,
		}
		if n, err := strconv.Atoi(c.CodeNum); err == nil {
			e.CodeNum = &n
		}
		entries = append(entries, e)
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].ISO2 < entries[j].ISO2 })

	name := *ts + "_seed_countries.sql"
	if err := writeFile(filepath.Join(*out, "sqlite", name), entries, dialectSQLite); err != nil {
		log.Fatal(err)
	}
	if err := writeFile(filepath.Join(*out, "mysql", name), entries, dialectMySQL); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("seedgen: wrote %d countries to sqlite + mysql migrations\n", len(entries))
}

type dialect int

const (
	dialectSQLite dialect = iota
	dialectMySQL
)

func writeFile(path string, entries []entry, d dialect) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return writeSQL(f, entries, d)
}

func writeSQL(w io.Writer, entries []entry, d dialect) error {
	header := "-- Generated by tools/seedgen from database/seed/countries.json\n-- Idempotent: re-running with the same input produces no schema change.\n\n"
	if _, err := io.WriteString(w, header); err != nil {
		return err
	}
	prefix := "INSERT OR IGNORE INTO"
	if d == dialectMySQL {
		prefix = "INSERT IGNORE INTO"
	}
	for _, e := range entries {
		fmt.Fprintf(
			w,
			"%s countries (iso2, iso3, ioc_code, name, code_num, population, area_km2, gdp_usd) VALUES (%s, %s, %s, %s, %s, %s, %s, NULL);\n",
			prefix,
			sqlStr(e.ISO2),
			sqlStr(e.ISO3),
			sqlStr(e.IOC),
			sqlStr(e.Name),
			sqlIntPtr(e.CodeNum),
			sqlInt64(e.Population),
			sqlFloat(e.AreaKm2),
		)
	}
	return nil
}

func sqlStr(s string) string {
	if s == "" {
		return "NULL"
	}
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

func sqlIntPtr(n *int) string {
	if n == nil {
		return "NULL"
	}
	return strconv.Itoa(*n)
}

func sqlInt64(n int64) string {
	if n == 0 {
		return "NULL"
	}
	return strconv.FormatInt(n, 10)
}

func sqlFloat(f float64) string {
	if f == 0 {
		return "NULL"
	}
	return strconv.FormatFloat(f, 'f', -1, 64)
}
