// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock_test.go -package=notifier
//

// Package notifier is a generated GoMock package.
package notifier

import (
	reflect "reflect"
	time "time"

	eventcore "github.com/jictyvoo/olhojogo/internal/domain/eventcore"
	gomock "go.uber.org/mock/gomock"
)

// MockFixtureReader is a mock of FixtureReader interface.
type MockFixtureReader struct {
	ctrl     *gomock.Controller
	recorder *MockFixtureReaderMockRecorder
	isgomock struct{}
}

// MockFixtureReaderMockRecorder is the mock recorder for MockFixtureReader.
type MockFixtureReaderMockRecorder struct {
	mock *MockFixtureReader
}

// NewMockFixtureReader creates a new mock instance.
func NewMockFixtureReader(ctrl *gomock.Controller) *MockFixtureReader {
	mock := &MockFixtureReader{ctrl: ctrl}
	mock.recorder = &MockFixtureReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFixtureReader) EXPECT() *MockFixtureReaderMockRecorder {
	return m.recorder
}

// ListFixturesStartingBefore mocks base method.
func (m *MockFixtureReader) ListFixturesStartingBefore(before time.Time) ([]eventcore.Fixture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFixturesStartingBefore", before)
	ret0, _ := ret[0].([]eventcore.Fixture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFixturesStartingBefore indicates an expected call of ListFixturesStartingBefore.
func (mr *MockFixtureReaderMockRecorder) ListFixturesStartingBefore(before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFixturesStartingBefore", reflect.TypeOf((*MockFixtureReader)(nil).ListFixturesStartingBefore), before)
}

// MockNotificationRepo is a mock of NotificationRepo interface.
type MockNotificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepoMockRecorder
	isgomock struct{}
}

// MockNotificationRepoMockRecorder is the mock recorder for MockNotificationRepo.
type MockNotificationRepoMockRecorder struct {
	mock *MockNotificationRepo
}

// NewMockNotificationRepo creates a new mock instance.
func NewMockNotificationRepo(ctrl *gomock.Controller) *MockNotificationRepo {
	mock := &MockNotificationRepo{ctrl: ctrl}
	mock.recorder = &MockNotificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepo) EXPECT() *MockNotificationRepoMockRecorder {
	return m.recorder
}

// GetLatestSentNotificationByAlert mocks base method.
func (m *MockNotificationRepo) GetLatestSentNotificationByAlert(alertID eventcore.CanonicalID) (eventcore.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestSentNotificationByAlert", alertID)
	ret0, _ := ret[0].(eventcore.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestSentNotificationByAlert indicates an expected call of GetLatestSentNotificationByAlert.
func (mr *MockNotificationRepoMockRecorder) GetLatestSentNotificationByAlert(alertID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestSentNotificationByAlert", reflect.TypeOf((*MockNotificationRepo)(nil).GetLatestSentNotificationByAlert), alertID)
}

// GetNotificationByChecksum mocks base method.
func (m *MockNotificationRepo) GetNotificationByChecksum(checksum string) (eventcore.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationByChecksum", checksum)
	ret0, _ := ret[0].(eventcore.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationByChecksum indicates an expected call of GetNotificationByChecksum.
func (mr *MockNotificationRepoMockRecorder) GetNotificationByChecksum(checksum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationByChecksum", reflect.TypeOf((*MockNotificationRepo)(nil).GetNotificationByChecksum), checksum)
}

// UpdateNotificationStatus mocks base method.
func (m *MockNotificationRepo) UpdateNotificationStatus(id eventcore.CanonicalID, status eventcore.NotificationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationStatus indicates an expected call of UpdateNotificationStatus.
func (mr *MockNotificationRepoMockRecorder) UpdateNotificationStatus(id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationStatus", reflect.TypeOf((*MockNotificationRepo)(nil).UpdateNotificationStatus), id, status)
}

// UpsertNotification mocks base method.
func (m *MockNotificationRepo) UpsertNotification(n eventcore.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertNotification", n)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertNotification indicates an expected call of UpsertNotification.
func (mr *MockNotificationRepoMockRecorder) UpsertNotification(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertNotification", reflect.TypeOf((*MockNotificationRepo)(nil).UpsertNotification), n)
}

// MockDispatcher is a mock of Dispatcher interface.
type MockDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockDispatcherMockRecorder
	isgomock struct{}
}

// MockDispatcherMockRecorder is the mock recorder for MockDispatcher.
type MockDispatcherMockRecorder struct {
	mock *MockDispatcher
}

// NewMockDispatcher creates a new mock instance.
func NewMockDispatcher(ctrl *gomock.Controller) *MockDispatcher {
	mock := &MockDispatcher{ctrl: ctrl}
	mock.recorder = &MockDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispatcher) EXPECT() *MockDispatcherMockRecorder {
	return m.recorder
}

// Edit mocks base method.
func (m *MockDispatcher) Edit(channelID, messageID, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Edit", channelID, messageID, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// Edit indicates an expected call of Edit.
func (mr *MockDispatcherMockRecorder) Edit(channelID, messageID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit", reflect.TypeOf((*MockDispatcher)(nil).Edit), channelID, messageID, content)
}

// Send mocks base method.
func (m *MockDispatcher) Send(channelID, content string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", channelID, content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockDispatcherMockRecorder) Send(channelID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockDispatcher)(nil).Send), channelID, content)
}

// MockChannelEnsurer is a mock of ChannelEnsurer interface.
type MockChannelEnsurer struct {
	ctrl     *gomock.Controller
	recorder *MockChannelEnsurerMockRecorder
	isgomock struct{}
}

// MockChannelEnsurerMockRecorder is the mock recorder for MockChannelEnsurer.
type MockChannelEnsurerMockRecorder struct {
	mock *MockChannelEnsurer
}

// NewMockChannelEnsurer creates a new mock instance.
func NewMockChannelEnsurer(ctrl *gomock.Controller) *MockChannelEnsurer {
	mock := &MockChannelEnsurer{ctrl: ctrl}
	mock.recorder = &MockChannelEnsurerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelEnsurer) EXPECT() *MockChannelEnsurerMockRecorder {
	return m.recorder
}

// ResolveChannel mocks base method.
func (m *MockChannelEnsurer) ResolveChannel(guildID, channelName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveChannel", guildID, channelName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveChannel indicates an expected call of ResolveChannel.
func (mr *MockChannelEnsurerMockRecorder) ResolveChannel(guildID, channelName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveChannel", reflect.TypeOf((*MockChannelEnsurer)(nil).ResolveChannel), guildID, channelName)
}

// MockMentionResolver is a mock of MentionResolver interface.
type MockMentionResolver struct {
	ctrl     *gomock.Controller
	recorder *MockMentionResolverMockRecorder
	isgomock struct{}
}

// MockMentionResolverMockRecorder is the mock recorder for MockMentionResolver.
type MockMentionResolverMockRecorder struct {
	mock *MockMentionResolver
}

// NewMockMentionResolver creates a new mock instance.
func NewMockMentionResolver(ctrl *gomock.Controller) *MockMentionResolver {
	mock := &MockMentionResolver{ctrl: ctrl}
	mock.recorder = &MockMentionResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMentionResolver) EXPECT() *MockMentionResolverMockRecorder {
	return m.recorder
}

// MentionsFor mocks base method.
func (m *MockMentionResolver) MentionsFor(guildID string, countryCodes []string, disciplineCode string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MentionsFor", guildID, countryCodes, disciplineCode)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MentionsFor indicates an expected call of MentionsFor.
func (mr *MockMentionResolverMockRecorder) MentionsFor(guildID, countryCodes, disciplineCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MentionsFor", reflect.TypeOf((*MockMentionResolver)(nil).MentionsFor), guildID, countryCodes, disciplineCode)
}

// MockFixtureContextReader is a mock of FixtureContextReader interface.
type MockFixtureContextReader struct {
	ctrl     *gomock.Controller
	recorder *MockFixtureContextReaderMockRecorder
	isgomock struct{}
}

// MockFixtureContextReaderMockRecorder is the mock recorder for MockFixtureContextReader.
type MockFixtureContextReaderMockRecorder struct {
	mock *MockFixtureContextReader
}

// NewMockFixtureContextReader creates a new mock instance.
func NewMockFixtureContextReader(ctrl *gomock.Controller) *MockFixtureContextReader {
	mock := &MockFixtureContextReader{ctrl: ctrl}
	mock.recorder = &MockFixtureContextReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFixtureContextReader) EXPECT() *MockFixtureContextReaderMockRecorder {
	return m.recorder
}

// GetFixtureContext mocks base method.
func (m *MockFixtureContextReader) GetFixtureContext(fixtureID eventcore.CanonicalID) (eventcore.FixtureContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFixtureContext", fixtureID)
	ret0, _ := ret[0].(eventcore.FixtureContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFixtureContext indicates an expected call of GetFixtureContext.
func (mr *MockFixtureContextReaderMockRecorder) GetFixtureContext(fixtureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFixtureContext", reflect.TypeOf((*MockFixtureContextReader)(nil).GetFixtureContext), fixtureID)
}

// MockCompetitorReader is a mock of CompetitorReader interface.
type MockCompetitorReader struct {
	ctrl     *gomock.Controller
	recorder *MockCompetitorReaderMockRecorder
	isgomock struct{}
}

// MockCompetitorReaderMockRecorder is the mock recorder for MockCompetitorReader.
type MockCompetitorReaderMockRecorder struct {
	mock *MockCompetitorReader
}

// NewMockCompetitorReader creates a new mock instance.
func NewMockCompetitorReader(ctrl *gomock.Controller) *MockCompetitorReader {
	mock := &MockCompetitorReader{ctrl: ctrl}
	mock.recorder = &MockCompetitorReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompetitorReader) EXPECT() *MockCompetitorReaderMockRecorder {
	return m.recorder
}

// ListFixtureCompetitors mocks base method.
func (m *MockCompetitorReader) ListFixtureCompetitors(fixtureID eventcore.CanonicalID) ([]eventcore.FixtureCompetitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFixtureCompetitors", fixtureID)
	ret0, _ := ret[0].([]eventcore.FixtureCompetitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFixtureCompetitors indicates an expected call of ListFixtureCompetitors.
func (mr *MockCompetitorReaderMockRecorder) ListFixtureCompetitors(fixtureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFixtureCompetitors", reflect.TypeOf((*MockCompetitorReader)(nil).ListFixtureCompetitors), fixtureID)
}
