// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock_test.go -package=notifier
//

// Package notifier is a generated GoMock package.
package notifier

import (
	reflect "reflect"
	time "time"

	eventcore "github.com/jictyvoo/olhojogo/internal/domain/eventcore"
	gomock "go.uber.org/mock/gomock"
)

// MockFixtureReader is a mock of FixtureReader interface.
type MockFixtureReader struct {
	ctrl     *gomock.Controller
	recorder *MockFixtureReaderMockRecorder
	isgomock struct{}
}

// MockFixtureReaderMockRecorder is the mock recorder for MockFixtureReader.
type MockFixtureReaderMockRecorder struct {
	mock *MockFixtureReader
}

// NewMockFixtureReader creates a new mock instance.
func NewMockFixtureReader(ctrl *gomock.Controller) *MockFixtureReader {
	mock := &MockFixtureReader{ctrl: ctrl}
	mock.recorder = &MockFixtureReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFixtureReader) EXPECT() *MockFixtureReaderMockRecorder {
	return m.recorder
}

// ListFixturesStartingBefore mocks base method.
func (m *MockFixtureReader) ListFixturesStartingBefore(before time.Time) ([]eventcore.Fixture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFixturesStartingBefore", before)
	ret0, _ := ret[0].([]eventcore.Fixture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFixturesStartingBefore indicates an expected call of ListFixturesStartingBefore.
func (mr *MockFixtureReaderMockRecorder) ListFixturesStartingBefore(before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFixturesStartingBefore", reflect.TypeOf((*MockFixtureReader)(nil).ListFixturesStartingBefore), before)
}

// MockNotificationRepo is a mock of NotificationRepo interface.
type MockNotificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepoMockRecorder
	isgomock struct{}
}

// MockNotificationRepoMockRecorder is the mock recorder for MockNotificationRepo.
type MockNotificationRepoMockRecorder struct {
	mock *MockNotificationRepo
}

// NewMockNotificationRepo creates a new mock instance.
func NewMockNotificationRepo(ctrl *gomock.Controller) *MockNotificationRepo {
	mock := &MockNotificationRepo{ctrl: ctrl}
	mock.recorder = &MockNotificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepo) EXPECT() *MockNotificationRepoMockRecorder {
	return m.recorder
}

// GetNotificationByChecksum mocks base method.
func (m *MockNotificationRepo) GetNotificationByChecksum(checksum string) (eventcore.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationByChecksum", checksum)
	ret0, _ := ret[0].(eventcore.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationByChecksum indicates an expected call of GetNotificationByChecksum.
func (mr *MockNotificationRepoMockRecorder) GetNotificationByChecksum(checksum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationByChecksum", reflect.TypeOf((*MockNotificationRepo)(nil).GetNotificationByChecksum), checksum)
}

// UpdateNotificationStatus mocks base method.
func (m *MockNotificationRepo) UpdateNotificationStatus(id eventcore.CanonicalID, status eventcore.NotificationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationStatus indicates an expected call of UpdateNotificationStatus.
func (mr *MockNotificationRepoMockRecorder) UpdateNotificationStatus(id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationStatus", reflect.TypeOf((*MockNotificationRepo)(nil).UpdateNotificationStatus), id, status)
}

// UpsertNotification mocks base method.
func (m *MockNotificationRepo) UpsertNotification(n eventcore.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertNotification", n)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertNotification indicates an expected call of UpsertNotification.
func (mr *MockNotificationRepoMockRecorder) UpsertNotification(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertNotification", reflect.TypeOf((*MockNotificationRepo)(nil).UpsertNotification), n)
}

// MockDispatcher is a mock of Dispatcher interface.
type MockDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockDispatcherMockRecorder
	isgomock struct{}
}

// MockDispatcherMockRecorder is the mock recorder for MockDispatcher.
type MockDispatcherMockRecorder struct {
	mock *MockDispatcher
}

// NewMockDispatcher creates a new mock instance.
func NewMockDispatcher(ctrl *gomock.Controller) *MockDispatcher {
	mock := &MockDispatcher{ctrl: ctrl}
	mock.recorder = &MockDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispatcher) EXPECT() *MockDispatcherMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockDispatcher) Send(channelID, content string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", channelID, content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockDispatcherMockRecorder) Send(channelID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockDispatcher)(nil).Send), channelID, content)
}

// MockMentionResolver is a mock of MentionResolver interface.
type MockMentionResolver struct {
	ctrl     *gomock.Controller
	recorder *MockMentionResolverMockRecorder
	isgomock struct{}
}

// MockMentionResolverMockRecorder is the mock recorder for MockMentionResolver.
type MockMentionResolverMockRecorder struct {
	mock *MockMentionResolver
}

// NewMockMentionResolver creates a new mock instance.
func NewMockMentionResolver(ctrl *gomock.Controller) *MockMentionResolver {
	mock := &MockMentionResolver{ctrl: ctrl}
	mock.recorder = &MockMentionResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMentionResolver) EXPECT() *MockMentionResolverMockRecorder {
	return m.recorder
}

// MentionsFor mocks base method.
func (m *MockMentionResolver) MentionsFor(guildID string, countryCodes []string, disciplineCode string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MentionsFor", guildID, countryCodes, disciplineCode)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MentionsFor indicates an expected call of MentionsFor.
func (mr *MockMentionResolverMockRecorder) MentionsFor(guildID, countryCodes, disciplineCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MentionsFor", reflect.TypeOf((*MockMentionResolver)(nil).MentionsFor), guildID, countryCodes, disciplineCode)
}

// MockResultReader is a mock of ResultReader interface.
type MockResultReader struct {
	ctrl     *gomock.Controller
	recorder *MockResultReaderMockRecorder
	isgomock struct{}
}

// MockResultReaderMockRecorder is the mock recorder for MockResultReader.
type MockResultReaderMockRecorder struct {
	mock *MockResultReader
}

// NewMockResultReader creates a new mock instance.
func NewMockResultReader(ctrl *gomock.Controller) *MockResultReader {
	mock := &MockResultReader{ctrl: ctrl}
	mock.recorder = &MockResultReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResultReader) EXPECT() *MockResultReaderMockRecorder {
	return m.recorder
}

// ListResultsByFixture mocks base method.
func (m *MockResultReader) ListResultsByFixture(fixtureID eventcore.CanonicalID) ([]eventcore.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResultsByFixture", fixtureID)
	ret0, _ := ret[0].([]eventcore.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResultsByFixture indicates an expected call of ListResultsByFixture.
func (mr *MockResultReaderMockRecorder) ListResultsByFixture(fixtureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResultsByFixture", reflect.TypeOf((*MockResultReader)(nil).ListResultsByFixture), fixtureID)
}

// MockCompetitionReader is a mock of CompetitionReader interface.
type MockCompetitionReader struct {
	ctrl     *gomock.Controller
	recorder *MockCompetitionReaderMockRecorder
	isgomock struct{}
}

// MockCompetitionReaderMockRecorder is the mock recorder for MockCompetitionReader.
type MockCompetitionReaderMockRecorder struct {
	mock *MockCompetitionReader
}

// NewMockCompetitionReader creates a new mock instance.
func NewMockCompetitionReader(ctrl *gomock.Controller) *MockCompetitionReader {
	mock := &MockCompetitionReader{ctrl: ctrl}
	mock.recorder = &MockCompetitionReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompetitionReader) EXPECT() *MockCompetitionReaderMockRecorder {
	return m.recorder
}

// GetCompetitionByFixture mocks base method.
func (m *MockCompetitionReader) GetCompetitionByFixture(fixtureID eventcore.CanonicalID) (eventcore.Competition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompetitionByFixture", fixtureID)
	ret0, _ := ret[0].(eventcore.Competition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompetitionByFixture indicates an expected call of GetCompetitionByFixture.
func (mr *MockCompetitionReaderMockRecorder) GetCompetitionByFixture(fixtureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompetitionByFixture", reflect.TypeOf((*MockCompetitionReader)(nil).GetCompetitionByFixture), fixtureID)
}

// MockParticipantReader is a mock of ParticipantReader interface.
type MockParticipantReader struct {
	ctrl     *gomock.Controller
	recorder *MockParticipantReaderMockRecorder
	isgomock struct{}
}

// MockParticipantReaderMockRecorder is the mock recorder for MockParticipantReader.
type MockParticipantReaderMockRecorder struct {
	mock *MockParticipantReader
}

// NewMockParticipantReader creates a new mock instance.
func NewMockParticipantReader(ctrl *gomock.Controller) *MockParticipantReader {
	mock := &MockParticipantReader{ctrl: ctrl}
	mock.recorder = &MockParticipantReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticipantReader) EXPECT() *MockParticipantReaderMockRecorder {
	return m.recorder
}

// ListParticipantsByFixture mocks base method.
func (m *MockParticipantReader) ListParticipantsByFixture(fixtureID eventcore.CanonicalID) ([]eventcore.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListParticipantsByFixture", fixtureID)
	ret0, _ := ret[0].([]eventcore.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListParticipantsByFixture indicates an expected call of ListParticipantsByFixture.
func (mr *MockParticipantReaderMockRecorder) ListParticipantsByFixture(fixtureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListParticipantsByFixture", reflect.TypeOf((*MockParticipantReader)(nil).ListParticipantsByFixture), fixtureID)
}
