// Code generated by MockGen. DO NOT EDIT.
// Source: render/render.go
//
// Generated by this command:
//
//	mockgen -source=render/render.go -destination=render_mock_test.go -package=notifier
//

// Package notifier is a generated GoMock package.
package notifier

import (
	reflect "reflect"

	render "github.com/jictyvoo/olhojogo/internal/domain/usecases/notifier/render"
	gomock "go.uber.org/mock/gomock"
)

// MockRenderer is a mock of Renderer interface.
type MockRenderer struct {
	ctrl     *gomock.Controller
	recorder *MockRendererMockRecorder
	isgomock struct{}
}

// MockRendererMockRecorder is the mock recorder for MockRenderer.
type MockRendererMockRecorder struct {
	mock *MockRenderer
}

// NewMockRenderer creates a new mock instance.
func NewMockRenderer(ctrl *gomock.Controller) *MockRenderer {
	mock := &MockRenderer{ctrl: ctrl}
	mock.recorder = &MockRendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRenderer) EXPECT() *MockRendererMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockRenderer) Render(view render.FixtureView) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", view)
	ret0, _ := ret[0].(string)
	return ret0
}

// Render indicates an expected call of Render.
func (mr *MockRendererMockRecorder) Render(view any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockRenderer)(nil).Render), view)
}
