// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbgen

import (
	"time"
)

type Competitor struct {
	ID        int64  `db:"id"`
	Name      string `db:"name"`
	Code      string `db:"code"`
	CountryID int64  `db:"country_id"`
}

type CountryInfo struct {
	ID          int64       `db:"id"`
	CreatedAt   time.Time   `db:"created_at"`
	UpdatedAt   time.Time   `db:"updated_at"`
	Code        string      `db:"code"`
	Name        string      `db:"name"`
	CodeNum     string      `db:"code_num"`
	IsoCodeLen2 interface{} `db:"iso_code_len2"`
	IsoCodeLen3 string      `db:"iso_code_len3"`
	IocCode     string      `db:"ioc_code"`
	Population  interface{} `db:"population"`
	AreaKm2     interface{} `db:"area_km2"`
	GdpUsd      interface{} `db:"gdp_usd"`
}

type NotifiedEvent struct {
	ID          int64       `db:"id"`
	EventSha256 string      `db:"event_sha256"`
	Status      string      `db:"status"`
	NotifiedAt  interface{} `db:"notified_at"`
	EventID     int64       `db:"event_id"`
}

type OlympicDiscipline struct {
	ID          int64       `db:"id"`
	Name        string      `db:"name"`
	Description interface{} `db:"description"`
}

type OlympicEvent struct {
	ID           int64     `db:"id"`
	EventName    string    `db:"event_name"`
	Phase        string    `db:"phase"`
	Gender       int64     `db:"gender"`
	SessionCode  string    `db:"session_code"`
	StartAt      time.Time `db:"start_at"`
	EndAt        time.Time `db:"end_at"`
	Status       string    `db:"status"`
	DisciplineID int64     `db:"discipline_id"`
}

type Result struct {
	ID           interface{} `db:"id"`
	Position     interface{} `db:"position"`
	Mark         interface{} `db:"mark"`
	MedalType    interface{} `db:"medal_type"`
	Irm          string      `db:"irm"`
	CompetitorID int64       `db:"competitor_id"`
	EventID      int64       `db:"event_id"`
}
