// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbgen

import (
	"time"
)

type Competitor struct {
	ID        int64  `db:"id"`
	Name      string `db:"name"`
	Code      string `db:"code"`
	CountryID int64  `db:"country_id"`
}

type CountryInfo struct {
	ID          int64       `db:"id"`
	CreatedAt   time.Time   `db:"created_at"`
	UpdatedAt   time.Time   `db:"updated_at"`
	Code        string      `db:"code"`
	Name        string      `db:"name"`
	CodeNum     string      `db:"code_num"`
	IsoCodeLen2 interface{} `db:"iso_code_len2"`
	IsoCodeLen3 string      `db:"iso_code_len3"`
	IocCode     string      `db:"ioc_code"`
	Population  interface{} `db:"population"`
	AreaKm2     interface{} `db:"area_km2"`
	GdpUsd      interface{} `db:"gdp_usd"`
}

type OlympicEvent struct {
	ID             int64     `db:"id"`
	EventName      string    `db:"event_name"`
	DisciplineName string    `db:"discipline_name"`
	Phase          string    `db:"phase"`
	Gender         int64     `db:"gender"`
	StartAt        time.Time `db:"start_at"`
	EndAt          time.Time `db:"end_at"`
	Status         string    `db:"status"`
}

type Result struct {
	ID           int64       `db:"id"`
	Position     interface{} `db:"position"`
	Mark         interface{} `db:"mark"`
	MedalType    interface{} `db:"medal_type"`
	Irm          string      `db:"irm"`
	CompetitorID int64       `db:"competitor_id"`
	EventID      int64       `db:"event_id"`
}
