// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competitions.sql

package dbgen

import (
	"context"
)

const GetCompetition = `-- name: GetCompetition :one
SELECT id, created_at, updated_at, provider_id, external_key, code, name, discipline FROM competitions WHERE id = ? LIMIT 1
`

func (q *Queries) GetCompetition(ctx context.Context, id []byte) (Competition, error) {
	row := q.db.QueryRowContext(ctx, GetCompetition, id)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.ExternalKey,
		&i.Code,
		&i.Name,
		&i.Discipline,
	)
	return i, err
}

const GetCompetitionByFixture = `-- name: GetCompetitionByFixture :one
SELECT c.id, c.created_at, c.updated_at, c.provider_id, c.external_key, c.code, c.name, c.discipline
FROM competitions c
JOIN seasons s ON s.competition_id = c.id
JOIN stages st ON st.season_id = s.id
JOIN fixtures f ON f.stage_id = st.id
WHERE f.id = ? LIMIT 1
`

func (q *Queries) GetCompetitionByFixture(ctx context.Context, id []byte) (Competition, error) {
	row := q.db.QueryRowContext(ctx, GetCompetitionByFixture, id)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.ExternalKey,
		&i.Code,
		&i.Name,
		&i.Discipline,
	)
	return i, err
}

const UpsertCompetition = `-- name: UpsertCompetition :exec
INSERT INTO competitions (
    id, provider_id, external_key, code, name, discipline,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, DATETIME('now'), DATETIME('now'))
ON CONFLICT(id) DO UPDATE SET
    code       = excluded.code,
    name       = excluded.name,
    discipline = excluded.discipline,
    updated_at = DATETIME('now')
`

type UpsertCompetitionParams struct {
	ID          []byte      `db:"id"`
	ProviderID  string      `db:"provider_id"`
	ExternalKey string      `db:"external_key"`
	Code        interface{} `db:"code"`
	Name        string      `db:"name"`
	Discipline  interface{} `db:"discipline"`
}

func (q *Queries) UpsertCompetition(ctx context.Context, arg UpsertCompetitionParams) error {
	_, err := q.db.ExecContext(ctx, UpsertCompetition,
		arg.ID,
		arg.ProviderID,
		arg.ExternalKey,
		arg.Code,
		arg.Name,
		arg.Discipline,
	)
	return err
}
