// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: competitions.sql

package dbgen

import (
	"context"
	"database/sql"
)

const GetCompetition = `-- name: GetCompetition :one
SELECT id, created_at, updated_at, provider_id, external_key, code, name, discipline FROM competitions WHERE id = ? LIMIT 1
`

func (q *Queries) GetCompetition(ctx context.Context, id []byte) (Competition, error) {
	row := q.db.QueryRowContext(ctx, GetCompetition, id)
	var i Competition
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.ExternalKey,
		&i.Code,
		&i.Name,
		&i.Discipline,
	)
	return i, err
}

const GetFixtureContext = `-- name: GetFixtureContext :one
SELECT
    c.code        AS competition_code,
    c.name        AS competition_name,
    c.discipline  AS discipline,
    st.name       AS stage_name,
    st.ord        AS stage_ord,
    g.name        AS group_name
FROM fixtures f
JOIN stages st      ON st.id = f.stage_id
JOIN seasons s      ON s.id = st.season_id
JOIN competitions c ON c.id = s.competition_id
LEFT JOIN groups g  ON g.id = f.group_id
WHERE f.id = ? LIMIT 1
`

type GetFixtureContextRow struct {
	CompetitionCode interface{}    `db:"competition_code"`
	CompetitionName string         `db:"competition_name"`
	Discipline      interface{}    `db:"discipline"`
	StageName       string         `db:"stage_name"`
	StageOrd        int64          `db:"stage_ord"`
	GroupName       sql.NullString `db:"group_name"`
}

func (q *Queries) GetFixtureContext(ctx context.Context, id []byte) (GetFixtureContextRow, error) {
	row := q.db.QueryRowContext(ctx, GetFixtureContext, id)
	var i GetFixtureContextRow
	err := row.Scan(
		&i.CompetitionCode,
		&i.CompetitionName,
		&i.Discipline,
		&i.StageName,
		&i.StageOrd,
		&i.GroupName,
	)
	return i, err
}

const UpsertCompetition = `-- name: UpsertCompetition :exec
INSERT INTO competitions (
    id, provider_id, external_key, code, name, discipline,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, DATETIME('now'), DATETIME('now'))
ON CONFLICT(id) DO UPDATE SET
    code       = excluded.code,
    name       = excluded.name,
    discipline = excluded.discipline,
    updated_at = DATETIME('now')
`

type UpsertCompetitionParams struct {
	ID          []byte      `db:"id"`
	ProviderID  string      `db:"provider_id"`
	ExternalKey string      `db:"external_key"`
	Code        interface{} `db:"code"`
	Name        string      `db:"name"`
	Discipline  interface{} `db:"discipline"`
}

func (q *Queries) UpsertCompetition(ctx context.Context, arg UpsertCompetitionParams) error {
	_, err := q.db.ExecContext(ctx, UpsertCompetition,
		arg.ID,
		arg.ProviderID,
		arg.ExternalKey,
		arg.Code,
		arg.Name,
		arg.Discipline,
	)
	return err
}
