// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Alert struct {
	ID        []byte    `db:"id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
	Kind      string    `db:"kind"`
	FixtureID []byte    `db:"fixture_id"`
}

type Competition struct {
	ID          []byte      `db:"id"`
	CreatedAt   time.Time   `db:"created_at"`
	UpdatedAt   time.Time   `db:"updated_at"`
	ProviderID  string      `db:"provider_id"`
	ExternalKey string      `db:"external_key"`
	Code        interface{} `db:"code"`
	Name        string      `db:"name"`
	Discipline  interface{} `db:"discipline"`
}

type Country struct {
	ID         int64       `db:"id"`
	Iso2       string      `db:"iso2"`
	Iso3       string      `db:"iso3"`
	IocCode    interface{} `db:"ioc_code"`
	Name       string      `db:"name"`
	CodeNum    interface{} `db:"code_num"`
	Population interface{} `db:"population"`
	AreaKm2    interface{} `db:"area_km2"`
	GdpUsd     interface{} `db:"gdp_usd"`
}

type DiscordEvent struct {
	ID             int64       `db:"id"`
	CreatedAt      time.Time   `db:"created_at"`
	UpdatedAt      time.Time   `db:"updated_at"`
	GuildID        string      `db:"guild_id"`
	DiscordEventID string      `db:"discord_event_id"`
	Status         string      `db:"status"`
	LastChecksum   interface{} `db:"last_checksum"`
	FixtureID      []byte      `db:"fixture_id"`
}

type Fixture struct {
	ID          []byte      `db:"id"`
	CreatedAt   time.Time   `db:"created_at"`
	UpdatedAt   time.Time   `db:"updated_at"`
	ProviderID  string      `db:"provider_id"`
	ExternalKey string      `db:"external_key"`
	GroupID     interface{} `db:"group_id"`
	VenueID     interface{} `db:"venue_id"`
	Name        string      `db:"name"`
	StartsAt    time.Time   `db:"starts_at"`
	EndsAt      time.Time   `db:"ends_at"`
	Status      string      `db:"status"`
	Checksum    interface{} `db:"checksum"`
	StageID     []byte      `db:"stage_id"`
}

type FixtureParticipant struct {
	ID            int64       `db:"id"`
	ParticipantID []byte      `db:"participant_id"`
	Role          interface{} `db:"role"`
	FixtureID     []byte      `db:"fixture_id"`
}

type Group struct {
	ID          []byte    `db:"id"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
	ProviderID  string    `db:"provider_id"`
	ExternalKey string    `db:"external_key"`
	Name        string    `db:"name"`
	StageID     []byte    `db:"stage_id"`
}

type Notification struct {
	ID        []byte      `db:"id"`
	CreatedAt time.Time   `db:"created_at"`
	UpdatedAt time.Time   `db:"updated_at"`
	ChannelID interface{} `db:"channel_id"`
	MessageID interface{} `db:"message_id"`
	Status    string      `db:"status"`
	Checksum  interface{} `db:"checksum"`
	SentAt    interface{} `db:"sent_at"`
	AlertID   []byte      `db:"alert_id"`
}

type Participant struct {
	ID          []byte      `db:"id"`
	CreatedAt   time.Time   `db:"created_at"`
	UpdatedAt   time.Time   `db:"updated_at"`
	ProviderID  string      `db:"provider_id"`
	ExternalKey string      `db:"external_key"`
	Kind        string      `db:"kind"`
	Name        string      `db:"name"`
	Code        interface{} `db:"code"`
	CountryIso  interface{} `db:"country_iso"`
	Gender      interface{} `db:"gender"`
}

type Result struct {
	ID            int64       `db:"id"`
	CreatedAt     time.Time   `db:"created_at"`
	UpdatedAt     time.Time   `db:"updated_at"`
	ParticipantID []byte      `db:"participant_id"`
	Position      interface{} `db:"position"`
	Score         interface{} `db:"score"`
	RawMark       interface{} `db:"raw_mark"`
	Outcome       interface{} `db:"outcome"`
	FixtureID     []byte      `db:"fixture_id"`
}

type Season struct {
	ID            []byte    `db:"id"`
	CreatedAt     time.Time `db:"created_at"`
	UpdatedAt     time.Time `db:"updated_at"`
	ProviderID    string    `db:"provider_id"`
	ExternalKey   string    `db:"external_key"`
	Name          string    `db:"name"`
	StartsOn      time.Time `db:"starts_on"`
	EndsOn        time.Time `db:"ends_on"`
	CompetitionID []byte    `db:"competition_id"`
}

type Stage struct {
	ID          []byte    `db:"id"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
	ProviderID  string    `db:"provider_id"`
	ExternalKey string    `db:"external_key"`
	Name        string    `db:"name"`
	Ord         int64     `db:"ord"`
	SeasonID    []byte    `db:"season_id"`
}

type Standing struct {
	ID            int64     `db:"id"`
	CreatedAt     time.Time `db:"created_at"`
	UpdatedAt     time.Time `db:"updated_at"`
	StageID       []byte    `db:"stage_id"`
	ParticipantID []byte    `db:"participant_id"`
	Rank          int64     `db:"rank"`
	Points        int64     `db:"points"`
}

type Subscription struct {
	ID        int64       `db:"id"`
	CreatedAt time.Time   `db:"created_at"`
	UpdatedAt time.Time   `db:"updated_at"`
	GuildID   string      `db:"guild_id"`
	UserID    string      `db:"user_id"`
	Kind      string      `db:"kind"`
	Value     interface{} `db:"value"`
}

type SyncState struct {
	ID           int64       `db:"id"`
	ProviderID   string      `db:"provider_id"`
	Scope        string      `db:"scope"`
	Cursor       interface{} `db:"cursor"`
	LastSyncedAt interface{} `db:"last_synced_at"`
	LastError    interface{} `db:"last_error"`
}

type Venue struct {
	ID          []byte      `db:"id"`
	CreatedAt   time.Time   `db:"created_at"`
	UpdatedAt   time.Time   `db:"updated_at"`
	ProviderID  string      `db:"provider_id"`
	ExternalKey string      `db:"external_key"`
	Name        string      `db:"name"`
	City        interface{} `db:"city"`
	CountryIso  interface{} `db:"country_iso"`
}
