// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package dbgen

import (
	"context"
)

const GetLatestSentNotificationByAlert = `-- name: GetLatestSentNotificationByAlert :one
SELECT id, created_at, updated_at, channel_id, message_id, status, checksum, sent_at, alert_id FROM notifications
WHERE alert_id = ? AND status = 'sent' AND message_id IS NOT NULL AND message_id <> ''
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestSentNotificationByAlert(ctx context.Context, alertID []byte) (Notification, error) {
	row := q.db.QueryRowContext(ctx, GetLatestSentNotificationByAlert, alertID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChannelID,
		&i.MessageID,
		&i.Status,
		&i.Checksum,
		&i.SentAt,
		&i.AlertID,
	)
	return i, err
}

const GetNotificationByChecksum = `-- name: GetNotificationByChecksum :one
SELECT id, created_at, updated_at, channel_id, message_id, status, checksum, sent_at, alert_id FROM notifications WHERE checksum = ? LIMIT 1
`

func (q *Queries) GetNotificationByChecksum(ctx context.Context, checksum interface{}) (Notification, error) {
	row := q.db.QueryRowContext(ctx, GetNotificationByChecksum, checksum)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChannelID,
		&i.MessageID,
		&i.Status,
		&i.Checksum,
		&i.SentAt,
		&i.AlertID,
	)
	return i, err
}

const GetNotificationByID = `-- name: GetNotificationByID :one
SELECT id, created_at, updated_at, channel_id, message_id, status, checksum, sent_at, alert_id FROM notifications WHERE id = ? LIMIT 1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id []byte) (Notification, error) {
	row := q.db.QueryRowContext(ctx, GetNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChannelID,
		&i.MessageID,
		&i.Status,
		&i.Checksum,
		&i.SentAt,
		&i.AlertID,
	)
	return i, err
}

const UpdateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notifications SET status = ?, updated_at = DATETIME('now') WHERE id = ?
`

type UpdateNotificationStatusParams struct {
	Status string `db:"status"`
	ID     []byte `db:"id"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.ExecContext(ctx, UpdateNotificationStatus, arg.Status, arg.ID)
	return err
}

const UpsertNotification = `-- name: UpsertNotification :exec
INSERT INTO notifications (id, alert_id, channel_id, message_id, status, checksum, sent_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, DATETIME('now'), DATETIME('now'))
ON CONFLICT(id) DO UPDATE SET
    status     = excluded.status,
    message_id = excluded.message_id,
    sent_at    = excluded.sent_at,
    updated_at = DATETIME('now')
`

type UpsertNotificationParams struct {
	ID        []byte      `db:"id"`
	AlertID   []byte      `db:"alert_id"`
	ChannelID interface{} `db:"channel_id"`
	MessageID interface{} `db:"message_id"`
	Status    string      `db:"status"`
	Checksum  interface{} `db:"checksum"`
	SentAt    interface{} `db:"sent_at"`
}

func (q *Queries) UpsertNotification(ctx context.Context, arg UpsertNotificationParams) error {
	_, err := q.db.ExecContext(ctx, UpsertNotification,
		arg.ID,
		arg.AlertID,
		arg.ChannelID,
		arg.MessageID,
		arg.Status,
		arg.Checksum,
		arg.SentAt,
	)
	return err
}
