// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seasons.sql

package dbgen

import (
	"context"
	"time"
)

const GetSeason = `-- name: GetSeason :one
SELECT id, created_at, updated_at, provider_id, external_key, name, starts_on, ends_on, competition_id FROM seasons WHERE id = ? LIMIT 1
`

func (q *Queries) GetSeason(ctx context.Context, id []byte) (Season, error) {
	row := q.db.QueryRowContext(ctx, GetSeason, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.ExternalKey,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.CompetitionID,
	)
	return i, err
}

const UpsertSeason = `-- name: UpsertSeason :exec
INSERT INTO seasons (
    id, provider_id, external_key, name, starts_on, ends_on, competition_id,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, DATETIME('now'), DATETIME('now'))
ON CONFLICT(id) DO UPDATE SET
    name           = excluded.name,
    starts_on      = excluded.starts_on,
    ends_on        = excluded.ends_on,
    competition_id = excluded.competition_id,
    updated_at     = DATETIME('now')
`

type UpsertSeasonParams struct {
	ID            []byte    `db:"id"`
	ProviderID    string    `db:"provider_id"`
	ExternalKey   string    `db:"external_key"`
	Name          string    `db:"name"`
	StartsOn      time.Time `db:"starts_on"`
	EndsOn        time.Time `db:"ends_on"`
	CompetitionID []byte    `db:"competition_id"`
}

func (q *Queries) UpsertSeason(ctx context.Context, arg UpsertSeasonParams) error {
	_, err := q.db.ExecContext(ctx, UpsertSeason,
		arg.ID,
		arg.ProviderID,
		arg.ExternalKey,
		arg.Name,
		arg.StartsOn,
		arg.EndsOn,
		arg.CompetitionID,
	)
	return err
}
