// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package dbgen

import (
	"context"
)

const AddSubscription = `-- name: AddSubscription :exec
INSERT INTO subscriptions (guild_id, user_id, kind, value, created_at, updated_at)
VALUES (?, ?, ?, ?, DATETIME('now'), DATETIME('now'))
ON CONFLICT(guild_id, user_id, kind, value) DO UPDATE SET
    updated_at = DATETIME('now')
`

type AddSubscriptionParams struct {
	GuildID string      `db:"guild_id"`
	UserID  string      `db:"user_id"`
	Kind    string      `db:"kind"`
	Value   interface{} `db:"value"`
}

func (q *Queries) AddSubscription(ctx context.Context, arg AddSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, AddSubscription,
		arg.GuildID,
		arg.UserID,
		arg.Kind,
		arg.Value,
	)
	return err
}

const ListSubscriptions = `-- name: ListSubscriptions :many
SELECT id, created_at, updated_at, guild_id, user_id, kind, value FROM subscriptions ORDER BY id ASC
`

func (q *Queries) ListSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, ListSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuildID,
			&i.UserID,
			&i.Kind,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSubscriptionsByGuild = `-- name: ListSubscriptionsByGuild :many
SELECT id, created_at, updated_at, guild_id, user_id, kind, value FROM subscriptions WHERE guild_id = ? ORDER BY id ASC
`

func (q *Queries) ListSubscriptionsByGuild(ctx context.Context, guildID string) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, ListSubscriptionsByGuild, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuildID,
			&i.UserID,
			&i.Kind,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSubscriptionsByGuildUser = `-- name: ListSubscriptionsByGuildUser :many
SELECT id, created_at, updated_at, guild_id, user_id, kind, value FROM subscriptions WHERE guild_id = ? AND user_id = ? ORDER BY id ASC
`

type ListSubscriptionsByGuildUserParams struct {
	GuildID string `db:"guild_id"`
	UserID  string `db:"user_id"`
}

func (q *Queries) ListSubscriptionsByGuildUser(ctx context.Context, arg ListSubscriptionsByGuildUserParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, ListSubscriptionsByGuildUser, arg.GuildID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GuildID,
			&i.UserID,
			&i.Kind,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveSubscription = `-- name: RemoveSubscription :exec
DELETE FROM subscriptions
WHERE guild_id = ? AND user_id = ? AND kind = ? AND value = ?
`

type RemoveSubscriptionParams struct {
	GuildID string      `db:"guild_id"`
	UserID  string      `db:"user_id"`
	Kind    string      `db:"kind"`
	Value   interface{} `db:"value"`
}

func (q *Queries) RemoveSubscription(ctx context.Context, arg RemoveSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, RemoveSubscription,
		arg.GuildID,
		arg.UserID,
		arg.Kind,
		arg.Value,
	)
	return err
}
