// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venues.sql

package dbgen

import (
	"context"
)

const GetVenue = `-- name: GetVenue :one
SELECT id, created_at, updated_at, provider_id, external_key, name, city, country_iso FROM venues WHERE id = ? LIMIT 1
`

func (q *Queries) GetVenue(ctx context.Context, id []byte) (Venue, error) {
	row := q.db.QueryRowContext(ctx, GetVenue, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.ExternalKey,
		&i.Name,
		&i.City,
		&i.CountryIso,
	)
	return i, err
}

const GetVenueByFixture = `-- name: GetVenueByFixture :one
SELECT v.id, v.created_at, v.updated_at, v.provider_id, v.external_key, v.name, v.city, v.country_iso
FROM venues v
JOIN fixtures f ON f.venue_id = v.id
WHERE f.id = ? LIMIT 1
`

func (q *Queries) GetVenueByFixture(ctx context.Context, id []byte) (Venue, error) {
	row := q.db.QueryRowContext(ctx, GetVenueByFixture, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderID,
		&i.ExternalKey,
		&i.Name,
		&i.City,
		&i.CountryIso,
	)
	return i, err
}

const UpsertVenue = `-- name: UpsertVenue :exec
INSERT INTO venues (
    id, provider_id, external_key, name, city, country_iso,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, DATETIME('now'), DATETIME('now'))
ON CONFLICT(id) DO UPDATE SET
    name        = excluded.name,
    city        = excluded.city,
    country_iso = excluded.country_iso,
    updated_at  = DATETIME('now')
`

type UpsertVenueParams struct {
	ID          []byte      `db:"id"`
	ProviderID  string      `db:"provider_id"`
	ExternalKey string      `db:"external_key"`
	Name        string      `db:"name"`
	City        interface{} `db:"city"`
	CountryIso  interface{} `db:"country_iso"`
}

func (q *Queries) UpsertVenue(ctx context.Context, arg UpsertVenueParams) error {
	_, err := q.db.ExecContext(ctx, UpsertVenue,
		arg.ID,
		arg.ProviderID,
		arg.ExternalKey,
		arg.Name,
		arg.City,
		arg.CountryIso,
	)
	return err
}
