// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock_test.go -package=discordsync
//

// Package discordsync is a generated GoMock package.
package discordsync

import (
	reflect "reflect"
	time "time"

	eventcore "github.com/jictyvoo/olhojogo/internal/domain/eventcore"
	discordfacade "github.com/jictyvoo/olhojogo/internal/infra/discordfacade"
	gomock "go.uber.org/mock/gomock"
)

// MockFixtureReader is a mock of FixtureReader interface.
type MockFixtureReader struct {
	ctrl     *gomock.Controller
	recorder *MockFixtureReaderMockRecorder
	isgomock struct{}
}

// MockFixtureReaderMockRecorder is the mock recorder for MockFixtureReader.
type MockFixtureReaderMockRecorder struct {
	mock *MockFixtureReader
}

// NewMockFixtureReader creates a new mock instance.
func NewMockFixtureReader(ctrl *gomock.Controller) *MockFixtureReader {
	mock := &MockFixtureReader{ctrl: ctrl}
	mock.recorder = &MockFixtureReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFixtureReader) EXPECT() *MockFixtureReaderMockRecorder {
	return m.recorder
}

// ListFixturesStartingBefore mocks base method.
func (m *MockFixtureReader) ListFixturesStartingBefore(before time.Time) ([]eventcore.Fixture, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFixturesStartingBefore", before)
	ret0, _ := ret[0].([]eventcore.Fixture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFixturesStartingBefore indicates an expected call of ListFixturesStartingBefore.
func (mr *MockFixtureReaderMockRecorder) ListFixturesStartingBefore(before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFixturesStartingBefore", reflect.TypeOf((*MockFixtureReader)(nil).ListFixturesStartingBefore), before)
}

// MockDiscordEventRepo is a mock of DiscordEventRepo interface.
type MockDiscordEventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordEventRepoMockRecorder
	isgomock struct{}
}

// MockDiscordEventRepoMockRecorder is the mock recorder for MockDiscordEventRepo.
type MockDiscordEventRepoMockRecorder struct {
	mock *MockDiscordEventRepo
}

// NewMockDiscordEventRepo creates a new mock instance.
func NewMockDiscordEventRepo(ctrl *gomock.Controller) *MockDiscordEventRepo {
	mock := &MockDiscordEventRepo{ctrl: ctrl}
	mock.recorder = &MockDiscordEventRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordEventRepo) EXPECT() *MockDiscordEventRepoMockRecorder {
	return m.recorder
}

// GetDiscordEventByFixture mocks base method.
func (m *MockDiscordEventRepo) GetDiscordEventByFixture(fixtureID eventcore.CanonicalID, guildID string) (eventcore.DiscordEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscordEventByFixture", fixtureID, guildID)
	ret0, _ := ret[0].(eventcore.DiscordEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscordEventByFixture indicates an expected call of GetDiscordEventByFixture.
func (mr *MockDiscordEventRepoMockRecorder) GetDiscordEventByFixture(fixtureID, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscordEventByFixture", reflect.TypeOf((*MockDiscordEventRepo)(nil).GetDiscordEventByFixture), fixtureID, guildID)
}

// UpdateDiscordEventStatus mocks base method.
func (m *MockDiscordEventRepo) UpdateDiscordEventStatus(fixtureID eventcore.CanonicalID, guildID string, status eventcore.DiscordEventStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDiscordEventStatus", fixtureID, guildID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDiscordEventStatus indicates an expected call of UpdateDiscordEventStatus.
func (mr *MockDiscordEventRepoMockRecorder) UpdateDiscordEventStatus(fixtureID, guildID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDiscordEventStatus", reflect.TypeOf((*MockDiscordEventRepo)(nil).UpdateDiscordEventStatus), fixtureID, guildID, status)
}

// UpsertDiscordEvent mocks base method.
func (m *MockDiscordEventRepo) UpsertDiscordEvent(de eventcore.DiscordEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDiscordEvent", de)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertDiscordEvent indicates an expected call of UpsertDiscordEvent.
func (mr *MockDiscordEventRepoMockRecorder) UpsertDiscordEvent(de any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDiscordEvent", reflect.TypeOf((*MockDiscordEventRepo)(nil).UpsertDiscordEvent), de)
}

// MockScheduledEventFacade is a mock of ScheduledEventFacade interface.
type MockScheduledEventFacade struct {
	ctrl     *gomock.Controller
	recorder *MockScheduledEventFacadeMockRecorder
	isgomock struct{}
}

// MockScheduledEventFacadeMockRecorder is the mock recorder for MockScheduledEventFacade.
type MockScheduledEventFacadeMockRecorder struct {
	mock *MockScheduledEventFacade
}

// NewMockScheduledEventFacade creates a new mock instance.
func NewMockScheduledEventFacade(ctrl *gomock.Controller) *MockScheduledEventFacade {
	mock := &MockScheduledEventFacade{ctrl: ctrl}
	mock.recorder = &MockScheduledEventFacadeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduledEventFacade) EXPECT() *MockScheduledEventFacadeMockRecorder {
	return m.recorder
}

// CancelScheduledEvent mocks base method.
func (m *MockScheduledEventFacade) CancelScheduledEvent(guildID, eventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelScheduledEvent", guildID, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelScheduledEvent indicates an expected call of CancelScheduledEvent.
func (mr *MockScheduledEventFacadeMockRecorder) CancelScheduledEvent(guildID, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelScheduledEvent", reflect.TypeOf((*MockScheduledEventFacade)(nil).CancelScheduledEvent), guildID, eventID)
}

// ListScheduledEvents mocks base method.
func (m *MockScheduledEventFacade) ListScheduledEvents(guildID string) ([]discordfacade.ScheduledEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScheduledEvents", guildID)
	ret0, _ := ret[0].([]discordfacade.ScheduledEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScheduledEvents indicates an expected call of ListScheduledEvents.
func (mr *MockScheduledEventFacadeMockRecorder) ListScheduledEvents(guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScheduledEvents", reflect.TypeOf((*MockScheduledEventFacade)(nil).ListScheduledEvents), guildID)
}

// CreateScheduledEvent mocks base method.
func (m *MockScheduledEventFacade) CreateScheduledEvent(guildID string, in discordfacade.ScheduledEventInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScheduledEvent", guildID, in)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScheduledEvent indicates an expected call of CreateScheduledEvent.
func (mr *MockScheduledEventFacadeMockRecorder) CreateScheduledEvent(guildID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScheduledEvent", reflect.TypeOf((*MockScheduledEventFacade)(nil).CreateScheduledEvent), guildID, in)
}

// UpdateScheduledEvent mocks base method.
func (m *MockScheduledEventFacade) UpdateScheduledEvent(guildID, eventID string, in discordfacade.ScheduledEventInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScheduledEvent", guildID, eventID, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScheduledEvent indicates an expected call of UpdateScheduledEvent.
func (mr *MockScheduledEventFacadeMockRecorder) UpdateScheduledEvent(guildID, eventID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScheduledEvent", reflect.TypeOf((*MockScheduledEventFacade)(nil).UpdateScheduledEvent), guildID, eventID, in)
}
