// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock_test.go -package=subscriptions
//

// Package subscriptions is a generated GoMock package.
package subscriptions

import (
	reflect "reflect"

	eventcore "github.com/jictyvoo/olhojogo/internal/domain/eventcore"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddSubscription mocks base method.
func (m *MockRepository) AddSubscription(sub eventcore.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSubscription", sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSubscription indicates an expected call of AddSubscription.
func (mr *MockRepositoryMockRecorder) AddSubscription(sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSubscription", reflect.TypeOf((*MockRepository)(nil).AddSubscription), sub)
}

// ListAll mocks base method.
func (m *MockRepository) ListAll() ([]eventcore.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll")
	ret0, _ := ret[0].([]eventcore.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockRepositoryMockRecorder) ListAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockRepository)(nil).ListAll))
}

// ListByGuild mocks base method.
func (m *MockRepository) ListByGuild(guildID string) ([]eventcore.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByGuild", guildID)
	ret0, _ := ret[0].([]eventcore.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByGuild indicates an expected call of ListByGuild.
func (mr *MockRepositoryMockRecorder) ListByGuild(guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByGuild", reflect.TypeOf((*MockRepository)(nil).ListByGuild), guildID)
}

// ListByGuildUser mocks base method.
func (m *MockRepository) ListByGuildUser(guildID, userID string) ([]eventcore.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByGuildUser", guildID, userID)
	ret0, _ := ret[0].([]eventcore.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByGuildUser indicates an expected call of ListByGuildUser.
func (mr *MockRepositoryMockRecorder) ListByGuildUser(guildID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByGuildUser", reflect.TypeOf((*MockRepository)(nil).ListByGuildUser), guildID, userID)
}

// RemoveSubscription mocks base method.
func (m *MockRepository) RemoveSubscription(sub eventcore.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSubscription", sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSubscription indicates an expected call of RemoveSubscription.
func (mr *MockRepositoryMockRecorder) RemoveSubscription(sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSubscription", reflect.TypeOf((*MockRepository)(nil).RemoveSubscription), sub)
}
